config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
 
  resources :articles
 
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
  end

  def edit
  end

  def create
    @article = Article.new(article_params)
 
    @article.save
    redirect_to @article
  end

  def update
  end

  def destroy
  end

  private
    def article_params
      params.require(:article).permit(:title, :text)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/index.html.slim
.row.column.align-center.text-center
  h1 Listing articles

.row.align-center.text-center
  .small-3.columns
    strong Title
  .small-7.columns
    strong Text
  .small-2.columns

- @articles.each do |article|
  .row.align-center.text-center
    .small-3.columns
      == article.title
    .small-7.columns
      == article.text
    .small-2.columns
      == link_to 'Show', article_path(article)

app/views/articles/new.html.slim
.row.columns.align-center.text-center
  h1 New Article

== form_for :article, url: articles_path do |f|
  .row.align-center
    .small-12.medium-6.columns
      p
        == f.label      :title
        == f.text_field :title

  .row.align-center
    .small-12.medium-6.columns
      p
        == f.label     :text
        == f.text_area :text
  
  .row.align-center.text-center
    .small-6.medium-4.columns
      a
        == f.submit

app/views/articles/show.html.slim
.row.align-center.text-center
  .columns
    h1
      == @article.title

.row.align-center.text-center
  .small-12.medium-6.columns
    p
      == @article.text

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang='en'>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : 'Blog' %></title>
    
    <meta charset='utf-8' />
    <meta name='viewport' content='width=device-width, initial-scale=1.0' />

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true%>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= yield %>

  </body>
</html>

app/views/welcome/index.html.slim
h1 Hello Rails